services:
  container1:
    build: ./container-1  
    ports:
      - "6000:6000"
    volumes:
      - shared-data:/data

  container2:
    build: ./container-2  
    ports:
      - "5001:5001"
    volumes:
      - shared-data:/data
    depends_on:
      - container1  

volumes:
  shared-data:
